[WIP] Use itext if select has media
XLSForm/pyxform pull request #467
Opened 2020-09-03 13:34 UTC by DavisRayM

Closes #464

#### Why is this the best possible solution? Were any other approaches considered?

#### What are the regression risks?

#### Does this change require updates to documentation? If so, please file an issue [here](https://github.com/XLSForm/xlsform.github.io) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] included test cases for core behavior and edge cases in `tests_v1`
- [ ] run `nosetests` and verified all tests pass
- [ ] run `black pyxform` to format code
- [ ] verified that any code or assets from external sources are properly credited in comments

2020-09-03 15:15 UTC, DavisRayM commented on pyxform/survey.py
> +                        ["static_instance", list_name, str(choice.get("name"))]
By default, the itextId is generated using `list_name` and `index` but I'm not entirely sure of a good way to retrieve the child's index from here. A possibility would be to iterate through the parents 'children'  key and determine this child's index but that seemed like a lot of processing time?

2020-09-03 15:16 UTC, DavisRayM commented on pyxform/survey_element.py
> +                    ["static_instance", parent.get("list_name"), self.get("name")]
By default, the itextId is generated using list_name and index but I'm not entirely sure of a good way to retrieve the child's index from here. A possibility would be to iterate through the parents 'children' key and determine this child's index but that seemed like it would take a lot of processing time?

2020-09-08 21:47 UTC, lognaturel requested changes
Thanks! It would be really helpful to get a high-level view of the decision points you came up to and some risk analysis. There are clearly ramifications if downstream tools use the itext ids in some way. I don't know how likely that is. DId you think through that?

If we're going to be changing the structure of the itext ids, we should consider alternatives. For example, we could use uuids for those identifiers instead of using the list and choice names. I don't really understand the `static_instance` prefix. If it's just noise, could we remove it?

2020-09-08 21:47 UTC, lognaturel commented on pyxform/tests_v1/test_translations.py
> +    def test_select_with_choice_filter_translation(self):
This test would pass on `master`, right? You want to make sure to have a test that would have failed so that it tests the new code paths. I think you can do that by removing the `label::Latin` column. I highly recommend using a test-driven approach in this code base -- typically it's possible to add tests without much refactor which is great! That way you can really go through the red-green-refactor cycle.

I would expect at the very least `test_select_with_media_and_choice_filter_and_no_translations_generates_media` and `test_select_with_choice_filter_and_translations_generates_single_translation` or something like that to capture the desired behavior for the two issues you're closing.

2020-09-08 21:47 UTC, lognaturel commented on pyxform/survey.py
> +                name = choice.get("name").replace(" ", "_")
Why add this? Wouldn't a name with a space fail earlier because it's not a valid XML identifier? If it's possible to have a name with a space in it, please add a test to cover that case.

2020-09-08 21:47 UTC, lognaturel commented on pyxform/survey.py
> +                itext_id = "-".join(["static_instance", list_name, name])
Is this change from index to name so that all identifiers have a consistent structure? Why is this important? Do you know what the `static_instance` prefix is supposed to mean (I don't). What are the implications of changing this for all translations?

2020-09-08 21:47 UTC, lognaturel commented on pyxform/xform2json.py
> +    def _get_list_name(self, itemset):
This doesn't look right. You should be able to get that instance name from the instance declaration.

2020-09-08 22:24 UTC, DavisRayM commented on pyxform/survey.py
> +                name = choice.get("name").replace(" ", "_")
It seemed to be possible for this [test](https://github.com/XLSForm/pyxform/blob/f79ade90b8196e1794ff8e078558c298a9771ea1/pyxform/tests_v1/test_inline_translations.py#L44), I'll need to confirm this though. I'll confirm and add a test if this is the case.

2020-09-08 22:42 UTC, DavisRayM commented on pyxform/survey.py
> +                itext_id = "-".join(["static_instance", list_name, name])
It's to make the ID construction more predictable. Noticed that the itext entry creation happens in multiple areas https://github.com/XLSForm/pyxform/blob/f79ade90b8196e1794ff8e078558c298a9771ea1/pyxform/survey.py#L594-L610 https://github.com/XLSForm/pyxform/blob/f79ade90b8196e1794ff8e078558c298a9771ea1/pyxform/survey.py#L613-L629 https://github.com/XLSForm/pyxform/blob/f79ade90b8196e1794ff8e078558c298a9771ea1/pyxform/survey.py#L651 using the name makes it a bit easier to recreate the IDs and stop duplicate entries from being created in other areas.

_Not entirely sure what the `static_instance` prefix means... Changing this for all translations related to choices(with multiple languages / media) would mean that all itext entries will have the `static_instance-<list_name>-<name>` format which seemed a bit more consistent and predictable, I don't believe this would affect any other functionality_

2020-09-08 22:50 UTC, DavisRayM commented on pyxform/xform2json.py
> +    def _get_list_name(self, itemset):
Mhm I might have been looking at the wrong area, I might have to look at the functionality that converts the XML to a dict. By this [point](https://github.com/XLSForm/pyxform/blob/50921a8e48b853565abd48b543558b5e24d6c4f4/pyxform/xform2json.py#L219) the `list_name`info doesn't seem to have been retrieved... Seems to just be a breakdown of the various sections of the XLSForm, didn't contain the `list_name` within it's contents.

2020-09-08 22:58 UTC, DavisRayM commented
> Thanks! It would be really helpful to get a high-level view of the decisions you made and some risk analysis. There are clearly ramifications if downstream tools use the itext ids in some way. I don't know how likely that is. Did you think through that?
> 
> If we're going to be changing the structure of the itext ids, we should consider alternatives. For example, we could use uuids for those identifiers instead of using the list and choice names. I don't really understand the `static_instance` prefix. If it's just noise, could we remove it?

I didn't think this would have any ramifications to be honest which might have been a rather naive viewpoint on my part. It seemed like some itext ids for choices where being generated in the `static_instance-<list_name>-<index>` format when a choice had multiple languages or choice filters and others generated using translation path of the element which didn't seem quite consistent which led to additional itext entries being created in other code locations. The `static_instance` format seemed a bit more easier to predict as such I kind of leaned towards that... I believe we can remove it... I'll work on this.

2020-09-09 01:19 UTC, DavisRayM commented
Closing this in favor of #468. _I didn't probably document my steps here or my reasoning for some of the changes. Most changes made here are actually not needed in order to fix the tagged issues. #468 is cleaner and I believe a bit more documented._

2020-09-09 01:19 UTC, closed without merging