Issue 471 deprecate unused device id methods
XLSForm/pyxform pull request #473
Opened 2020-10-11 03:12 UTC by KeynesYouDigIt

Closes #471 

#### Why is this the best possible solution? Were any other approaches considered?
This adds warnings where other question type specific warnings are. This pattern is modelled after the special validation work used for 'audit' and 'calculate' question types.

I considered checking this information upstream in the survey creation process, but would have to re-divide the sheet into rows. Downstream, during question creation and final survey creation, is another place where warnings can be generated, but we have the information we need at the point where the warnings were added, so no point in working further down.

#### What are the regression risks?
I did modify constants.py - any modification of a global config represents some regression risk. However, values were only added, and only values that apply to my use case, and only under a name that does not conflict with another name, so I do not see any great risks.

#### Does this change require updates to documentation? If so, please file an issue [here](https://github.com/XLSForm/xlsform.github.io) and include the link below.
docs should already be set https://github.com/XLSForm/xlsform.github.io/pull/208/files

#### Before submitting this PR, please make sure you have:
- [ x ] included test cases for core behavior and edge cases in `tests_v1`
- [ x ] run `nosetests` and verified all tests pass
- [ x ] run `black pyxform` to format code
- [ x ] verified that any code or assets from external sources are properly credited in comments

2020-10-11 03:14 UTC, KeynesYouDigIt commented on pyxform/tests/xlsform_spec_test.py
> +            len(warnings), 22, "Found " + str(len(warnings)) + " warnings"
I thought about just removing the simserial reference from the excel file used in this test, is that a better way to go since simserial is technically not a part of the spec anymore? Should this file be updated for new spec stuff?

2020-10-11 03:15 UTC, KeynesYouDigIt commented on pyxform/tests_v1/test_metadata.py
> +        self.assertPyxformXform(
boy scout rule :) thought I would throw a test in for these fields getting their `preloadParams`, LMK if this is unhelpful in any way.

2020-10-14 16:26 UTC, lognaturel requested changes
Looking good!

2020-10-14 16:26 UTC, lognaturel commented on pyxform/tests/xlsform_spec_test.py
> +            len(warnings), 22, "Found " + str(len(warnings)) + " warnings"
I like your idea of removing it since it's no longer part of the spec!

2020-10-14 16:26 UTC, lognaturel commented on pyxform/tests_v1/test_metadata.py
> +        self.assertPyxformXform(
👍 I like it.

2020-10-14 16:26 UTC, lognaturel commented on pyxform/tests_v1/test_metadata.py
> +            |        | subscriberid | subscriberid             | sub id is not lable optional I guess       |
> sub id is not lable optional I guess

It should be. Does it fail with a real form converted by pyxform master without a label?

2020-10-17 20:43 UTC, KeynesYouDigIt commented on pyxform/tests_v1/test_metadata.py
> +            |        | subscriberid | subscriberid             | sub id is not lable optional I guess       |
its just a warning not an error, but I get this warning. I will clarify that in the label and comments

```row : 2] Question has no label: {'name': 'subscriberid', 'type': 'subscriberid'}```

2020-10-17 20:46 UTC, KeynesYouDigIt commented on pyxform/tests_v1/test_metadata.py
> +            |        | subscriberid | subscriberid             | sub id is not lable optional I guess       |
I could also do the work to remove this warning, but it doesnt seem pertinent since sub id is being deprecated

2020-10-17 22:00 UTC, KeynesYouDigIt commented on pyxform/tests/xlsform_spec_test.py
> +            len(warnings), 22, "Found " + str(len(warnings)) + " warnings"
Should be all done!

2020-10-19 17:07 UTC, lognaturel approved these changes
Super, thanks so much!!

2020-10-19 17:07 UTC, merged