Options contains ${node} references and choice filter and no translation should generate itext fields.
XLSForm/pyxform pull request #518
Opened 2021-02-17 08:09 UTC by gushil

Closes #515
 
#### Why is this the best possible solution? Were any other approaches considered?
The simplest one that works.

#### What are the regression risks?
None. All tests are passed.

#### Does this change require updates to documentation? If so, please file an issue [here](https://github.com/XLSForm/xlsform.github.io) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] included test cases for core behavior and edge cases in `tests_v1`
- [x] run `nosetests` and verified all tests pass
- [x] run `black pyxform` to format code
- [x] verified that any code or assets from external sources are properly credited in comments

2021-02-17 18:25 UTC, lognaturel commented
The general approach here is to iterate through all the labels for a list that has a choice filter and if any of them has a reference, generate `itext` for that list. This adds yet more special cases and I think will have a noticeable performance impact on forms with really long choice lists that don't use any references in labels. It's not unusual to have thousands of choices for filtered lists and the typical case is not to have references.

Here are a couple more approaches to consider:
- Only check the first item in a list with a choice filter and generate `itext` only if that first choice has a label with a ref. That doesn't slow down the common case and I have a hard time imagining a case where someone would want a mix of labels with references and labels without. We still end up needing some special cases but with comments we can mitigate some of that.
- Always generate `itext` for lists with filters. The big advantage is that it's simpler. I don't love that it will often unecessarily increase the size of the XML and I know Enketo has trouble with forms with `itext` so this is probably not a good option but maybe I'm missing something.

@MartijnR what do you think?

2021-02-17 18:51 UTC, pbowen-oc commented
@lognaturel - I do not have a specific real-world example for your first bullet point, but I could definitely see codes like the following:
name label filter
0 "Event not related to any medication" 0
1 "Event related to ${medication1}" 1
2 "Event related to ${medication2}" 2
3 "Event related to ${medication3}" 3

If that approach were taken, I suppose a workaround in this case would be to add an item reference to a null calculated item to the first choice. I think that could work from a form design perspective, but would not be ideal.

2021-02-17 22:04 UTC, MartijnR commented
Thanks @gushil and @lognaturel. 

Good point about the potential performance issue with thousands of items (and generally not using outputs, especially not in those long lists). 

Of your suggestions, my preference would be to use a trick such as you proposed in your first approach and keep the XML output clean for the common use cases without outputs. @pbowen-oc's concern that the first option may be the odd one that doesn't use an output, is a good point. So how about we check the first 2 to be 99.9% sure (or first 10 to be 99.999999% sure)? 

I'm guessing a non-global regex test of the unparsed choices **per list** is not an option, right?

2021-02-17 22:37 UTC, lognaturel commented
> we check the first 2 to be 99.9% sure

I'm happy with that. I'd also be happy documenting that for a choice list labels to be treated as dynamic, the first item's label must be dynamic. I think @pbowen-oc's example is realistic but it seems the non-dynamic label could also go last.

> non-global regex test of the unparsed choices per list

I'm not sure I know what that means! Do you mean doing a regex on the text of all the choice labels together? I don't think there's a performant way to do that.

2021-02-17 23:00 UTC, MartijnR commented
> I'm not sure I know what that means! 

I think maybe it makes more sense in Dutch? 😂 But you actually parsed that correctly. Let's forget about that idea.

2021-02-17 23:08 UTC, lognaturel commented
> I think maybe it makes more sense in Dutch? 😂

😄😄 I thought "non-global regex" might be some technical concept I didn't know about. I think it'd work if we had all choices as text but coming out of a spreadsheet they're in a collection.

2021-02-18 14:27 UTC, gushil commented
Hi @lognaturel and @MartijnR 

Thanks for the very useful comments. I've made some changes to accommodate that. Hoping to get some review again.

Thanks!

2021-02-22 22:37 UTC, MartijnR requested changes
I did a partial review, mostly by performing some transformations, and a quick glance at the code. I found one issue.

2021-02-22 22:37 UTC, MartijnR commented on pyxform/survey.py
> +        return bracketed_tag_in_choice_label
I think this algorithm is not quite right. If **any** of the first two choices contains a bracketed tag, it should generate outputs. Will propose a tweak to the test below, to catch this.

2021-02-22 22:37 UTC, MartijnR commented on pyxform/tests_v1/test_inline_translations.py
> +        |         | choices   | one  | One - ${txt} |
Change this label to "One" without a ${txt} reference to catch a bug in the current PR.

2021-02-23 09:35 UTC, gushil commented on pyxform/survey.py
> +        return bracketed_tag_in_choice_label
Thanks for the review. Fixed in the next commit.

2021-02-23 09:35 UTC, gushil commented on pyxform/tests_v1/test_inline_translations.py
> +        |         | choices   | one  | One - ${txt} |
Added test to include this case in the next commit.

2021-02-23 18:19 UTC, MartijnR requested changes

2021-02-23 18:19 UTC, MartijnR commented on pyxform/tests_v1/test_inline_translations.py
> +        )
Now, I'm seeing this one fail (accidentally, when randomly testing):

list_name | name | label
-- | -- | --
choices | one | One - {txt}
choices | two | Two
yes_no | yes | Yes  - ${txt}
yes_no | no | No

type | name | label | choice_filter | default
-- | -- | -- | -- | --
text | txt | Enter text |   | default
select_one choices | one | Select one | 1 < 2 |  
select_one yes_no | yn | Yes or no? | 1 < 2 |  

It works for the `yes_no` list but not for the `choices` list.

2021-02-24 09:42 UTC, gushil commented on pyxform/tests_v1/test_inline_translations.py
> +        )
@MartijnR I see that the label for choices one is 'One - {txt}' not 'One - ${txt}'. Is that intentional?

2021-02-24 16:34 UTC, MartijnR commented on pyxform/tests_v1/test_inline_translations.py
> +        )
No bug. Sorry about that! That explains why I couldn't figure out the cause from the code.

2021-02-24 16:35 UTC, MartijnR reviewed
I think this is ready for a real review!

2021-02-24 22:17 UTC, MartijnR approved these changes

2021-02-25 19:12 UTC, lognaturel reviewed
I think there are some leftovers from previous solutions. I propose #521 as a simplification.

2021-02-25 19:12 UTC, lognaturel commented on pyxform/question.py
> +                for choice in choices[itemset]:
This iterates over all choices.

2021-02-25 19:12 UTC, lognaturel commented on pyxform/survey.py
> +                if has_choice_filter_and_referenced_choice_label:
I don't understand what these changes are for.

2021-02-25 19:12 UTC, lognaturel commented on pyxform/survey.py
> +            if parent:
It's not clear to me what these changes are for.

2021-02-26 03:33 UTC, gushil commented on pyxform/question.py
> +                for choice in choices[itemset]:
I see. I try not to change original code. Yeah, this is iterates over all choices.

2021-02-26 03:36 UTC, gushil commented on pyxform/survey.py
> +                if has_choice_filter_and_referenced_choice_label:
That is for generating itextId with just name if the choices have a choice_filter applied and referenced label in it.

2021-02-26 03:39 UTC, gushil commented on pyxform/survey.py
> +            if parent:
That is from the original code. It will check whether current element we are checking have a parent. From what I saw, this applied to survey element and choices, and not element in settings.

2021-02-26 03:53 UTC, gushil commented on pyxform/survey.py
> +                if has_choice_filter_and_referenced_choice_label:
I saw that PR #521 still generating instance with itextId, label, name not itextId and name.

2021-02-26 03:58 UTC, gushil commented on pyxform/survey.py
> +            if parent:
I use this one to check if the current element has choice_filter in it.

2021-02-26 04:18 UTC, lognaturel commented on pyxform/survey.py
> +                if has_choice_filter_and_referenced_choice_label:
Ahh, great, that makes sense. Thanks for spotting that. Goes to show how important it is to have test coverage for requirements like that. [`5362a8f` (#521)](https://github.com/XLSForm/pyxform/pull/521/commits/5362a8f25749df9f6692eb78a94c96c279a9772d) should address it and add test coverage.

I think your approach here would drop additional data columns for lists with dynamic labels. I added a test for that case at https://github.com/XLSForm/pyxform/pull/521/commits/5362a8f25749df9f6692eb78a94c96c279a9772d#diff-c18988116c2ca8b0df3613f683c25a7f7eeb871dc823c2697be5db1d3f38a9acR213.

2021-02-26 04:19 UTC, lognaturel commented on pyxform/survey.py
> +            if parent:
Can you think of a test that would fail without this change?

2021-02-26 04:30 UTC, lognaturel commented on pyxform/question.py
> +                for choice in choices[itemset]:
I think https://github.com/XLSForm/pyxform/pull/521/files#diff-70c36a8d1a06302bbc77d3189fb1a736d02802a2c789f7687cc9e3458628bd1dR218 achieves maintaining existing code and avoiding the iteration.

2021-02-26 04:33 UTC, lognaturel commented on pyxform/survey.py
> +                except IndexError:
See https://github.com/XLSForm/pyxform/pull/521/files#diff-633c22eb8bd15e90567dcd0d93daf7e6ad79a27b5d55e827f7335b6178806374R279 for a way to capture the semantics of what we're trying to do without risking an index error.

2021-02-26 04:44 UTC, gushil commented on pyxform/survey.py
> +                except IndexError:
That line is perfect 👍 
I learned a lot. Thanks.

2021-02-26 04:50 UTC, gushil commented on pyxform/survey.py
> +            if parent:
Hmm, previously I'm not changing this line and I got a couple of test errors. But I check your PR that doing exactly that (not changing anything) and all the tests passed. So I'm assuming all the cases are covered?

2021-02-26 04:51 UTC, gushil commented on pyxform/survey.py
> +                if has_choice_filter_and_referenced_choice_label:
So, it looks like we don't have to check choice_filter right?

2021-02-26 04:54 UTC, gushil commented on pyxform/survey.py
> +                if has_choice_filter_and_referenced_choice_label:
Ah, so that's why I don't get remaining columns.

2021-02-26 04:54 UTC, gushil commented on pyxform/survey.py
> +                if has_choice_filter_and_referenced_choice_label:
So, it looks like we don't really need to check choice_filter column at all for this case?

2021-02-26 06:10 UTC, gushil commented on pyxform/question.py
> +                for choice in choices[itemset]:
Yes, I agree with that.

2021-02-26 22:46 UTC, lognaturel commented on pyxform/survey.py
> +                if has_choice_filter_and_referenced_choice_label:
I can't think of a reason why we would. This code appears in `_generate_static_instances` which is only called for select choice lists that were already determined to need an `instance`. That decision is made earlier based on whether there's a choice filter.

I added a test supporting this reasoning at https://github.com/XLSForm/pyxform/pull/521/files#diff-48adf053262e50c0e674ecc7abaf998386e3ba08ff96c4b4327a84b423a307a0R231. I also verified that the test passes on `master` so that behavior hasn't changed.

2021-02-26 22:48 UTC, lognaturel commented on pyxform/survey.py
> +            if parent:
All the same tests definitely pass so it's a question of whether we forgot any cases! My guess is that some of this is related to the conversation above and thinking we need to differentiate between selects that need secondary instances and those that don't.

2021-02-26 22:48 UTC, lognaturel commented
Let's close this in favor of #521 and apply what we've learned there.

2021-02-26 22:48 UTC, closed without merging