Add support for odk:recordaction
XLSForm/pyxform pull request #519
Opened 2021-02-17 17:12 UTC by seadowg

Closes #

#### Why is this the best possible solution? Were any other approaches considered?

#### What are the regression risks?

#### Does this change require updates to documentation? If so, please file an issue [here](https://github.com/XLSForm/xlsform.github.io) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] included test cases for core behavior and edge cases in `tests_v1`
- [ ] run `nosetests` and verified all tests pass
- [ ] run `black pyxform` to format code
- [ ] verified that any code or assets from external sources are properly credited in comments

2021-02-17 17:16 UTC, seadowg commented on pyxform/tests_v1/pyxform_test_case.py
> +                msg_prefix + "Couldn't find %s in content:\n" % text_repr + content,
I found I was really unclear on what exactly I was doing wrong in my implementation and adding the content here really helped me.

2021-02-17 17:30 UTC, lognaturel commented on pyxform/tests_v1/pyxform_test_case.py
> +                msg_prefix + "Couldn't find %s in content:\n" % text_repr + content,
If I understand this correctly, I think what I usually do for this is turn on `debug=True`. I find that's a good sanity check anyway and usually have it on when adding a new test.

Would this make more sense as `Couldn't find %s in content %s:\n" % text_repr, content` or something? I should actually try it...

2021-02-17 17:34 UTC, lognaturel commented on pyxform/tests_v1/pyxform_test_case.py
> +                msg_prefix + "Couldn't find %s in content:\n" % text_repr + content,
Ok, I see, the format is actually what I'd expect. But I think it is redundant with `debug=True`.

2021-02-17 17:38 UTC, lognaturel requested changes
Looks good, just a few things!

2021-02-17 17:38 UTC, lognaturel commented on pyxform/question_type_dictionary.py
> +        "control": {"tag": "action"},
I think you'l also need a `"bind": {"type": "binary"}` here.

2021-02-17 17:38 UTC, lognaturel commented on pyxform/tests_v1/test_background_audio.py
> +                '<odk:recordaudio event="odk-instance-load" ref="/data/my_recording"/>',
Should also test for `<bind ref="/data/my_recording" type="binary"/>`

2021-02-17 17:38 UTC, lognaturel commented on pyxform/tests_v1/test_background_audio.py
> +    @unittest.skip("Required update to Validate to work")
We won't want this as part of the test suite because running Validate is time-consuming. Instead we run all tests with Validate as part of review and as a sanity check before release. Should probably automate that some day but it's not a big deal for now.

2021-02-17 17:46 UTC, seadowg commented on pyxform/tests_v1/test_background_audio.py
> +                '<odk:recordaudio event="odk-instance-load" ref="/data/my_recording"/>',
Ah actually yeah I was meaning to ask about that. We don't include anything about `bind` in the final example in the [spec discussion](https://forum.getodk.org/t/form-spec-proposal-add-background-audio-recording/31889/21) and we also haven't included it in [tests for Collect](https://github.com/getodk/collect/blob/master/collect_app/src/androidTest/assets/forms/one-question-background-audio.xml). Do we just need it for correctness? Hoping there's nothing wrong with the Collect implementation 🤞.

2021-02-17 18:04 UTC, lognaturel commented on pyxform/tests_v1/test_background_audio.py
> +                '<odk:recordaudio event="odk-instance-load" ref="/data/my_recording"/>',
It's important for tools that might treat answers of different types differently, usually servers. Form filling clients probably don't care. The default bind type is `string` and that's fine for a file names.

2021-02-17 18:05 UTC, seadowg commented on pyxform/tests_v1/test_background_audio.py
> +                '<odk:recordaudio event="odk-instance-load" ref="/data/my_recording"/>',
Ah right but the server needs to know it's `binary`. I see!

2021-02-17 18:12 UTC, seadowg commented on pyxform/tests_v1/pyxform_test_case.py
> +                msg_prefix + "Couldn't find %s in content:\n" % text_repr + content,
It seems strange to me to only output the content optionally. Wouldn't you always want to know if it fails what the resulting XForm looked like? Also, as much as it does the right thing it's a bit of a secret that you can use the `debug` parameter here.

2021-02-17 18:30 UTC, lognaturel commented on pyxform/tests_v1/test_background_audio.py
> +                '<odk:recordaudio event="odk-instance-load" ref="/data/my_recording"/>',
Yeah, the way we've written the XForms spec, the action should only have any effect if the `ref` is of type `binary`. We're more lenient than that at the moment in JR/Collect. I think that's ok if manual XML writers really want to do crazy things but it's important that form builders provide all the info.

2021-02-17 18:31 UTC, lognaturel approved these changes

2021-02-17 18:31 UTC, lognaturel commented on pyxform/tests_v1/pyxform_test_case.py
> +                msg_prefix + "Couldn't find %s in content:\n" % text_repr + content,
🤷🏻‍♀️ Fair enough!

2021-02-17 18:32 UTC, merged

2021-02-17 18:34 UTC, lognaturel commented on pyxform/tests_v1/test_background_audio.py
> +                '<odk:recordaudio event="odk-instance-load" ref="/data/my_recording"/>',
("all the info" = "this node actually represents a binary file so treat its value as a filename, not just a string")

2021-02-17 23:13 UTC, lognaturel commented
@MartijnR it occurs to me you might like (and it might be a good idea) to do a sanity check on this.

2021-02-18 22:35 UTC, MartijnR commented
Thanks. I had a quick look at the tests. All looks good to me!