Add support for csv-external
XLSForm/pyxform pull request #522
Opened 2021-02-25 22:47 UTC by lognaturel

Closes #271

#### Why is this the best possible solution? Were any other approaches considered?
Uses the same code paths as `xml-external` which reduces risk. I briefly considered treating them differently in some way but that seemed more complex for no payoff.

I tried to come up with the minimal tests we needed to validate the addition. Since the same code is used as with `xml-external`, I think a lot of the cases are already handled but please be on the lookout for anything that might not be covered.

I noticed some tests were configured to always run Validate. We've discussed not doing that to speed up the test suite so I removed that. We always run all tests with Validate before a release. I also added a commit to make sure all tests pass Validate because failures were mostly in the test file I was already in.

#### What are the regression risks?
This is an additive change and I don't see a regression risk. The only existing code that has changed has to do with `xml-external` and that has really good test coverage.

#### Does this change require updates to documentation? If so, please file an issue [here](https://github.com/XLSForm/xlsform.github.io) and include the link below.
https://github.com/XLSForm/xlsform.github.io/issues/216

#### Before submitting this PR, please make sure you have:
- [x] included test cases for core behavior and edge cases in `tests_v1`
- [x] run `nosetests` and verified all tests pass
- [x] run `black pyxform` to format code
- [x] verified that any code or assets from external sources are properly credited in comments

2021-02-26 10:05 UTC, ukanga approved these changes

2021-02-26 17:11 UTC, MartijnR requested changes
Very exciting feature! Thanks!

We should do `jr://file-csv/name.csv` and this what we use with pulldata in pyxform as well. 

https://getodk.github.io/xforms-spec/#file-endpoints

2021-02-26 22:50 UTC, lognaturel commented
> We should do jr://file-csv/name.csv

I completely forgot about that, you're absolutely right! 😬

2021-02-26 23:10 UTC, lognaturel commented
Thanks for remembering that, @MartijnR. I'm a little shaken that https://github.com/XLSForm/pyxform/pull/522/files#diff-8ca5f58100688d382c2625d49faf9b321a0edd1f4dd98526bc8e71d0f11ab4e8R176 didn't catch that. I was thinking it would help us know the generated instance declarations would be identical. I now see there's only a check for an instance name conflict so it doesn't really cover us that much.

2021-03-01 17:38 UTC, MartijnR submitted a review, later dismissed
Thanks!

2021-03-26 20:51 UTC, lognaturel commented
I rebased on master which auto fixed merge conflicts.

2021-03-26 20:54 UTC, merged