${} references in predicates should be expanded using current()
XLSForm/pyxform pull request #524
Opened 2021-03-03 14:12 UTC by gushil

Closes #490 

#### Why is this the best possible solution? Were any other approaches considered?
I use simple predicate testing by checking whether current context start with `instance(`. I'm thinking about xpath parser, but thought that would be too overkill for this case.

#### What are the regression risks?
None, but probably still need some more tests. Open to more tests suggestion!

#### Does this change require updates to documentation? If so, please file an issue [here](https://github.com/XLSForm/xlsform.github.io) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] included test cases for core behavior and edge cases in `tests_v1`
- [x] run `nosetests` and verified all tests pass
- [x] run `black pyxform` to format code
- [x] verified that any code or assets from external sources are properly credited in comments

2021-03-04 20:42 UTC, MartijnR reviewed
I've not been able to break this 3-line solution 😄 

I added some tests to the issue, that may be helpful if this code ever gets refactored.

2021-03-04 20:42 UTC, MartijnR commented on pyxform/survey.py
> +        is_predicate = matchobj.string.startswith("instance(")
This is quite an original solution to 

> figuring out the least hacky/most performant way to identify that we're expanding a reference in a predicate

This `is_predicate` doesn't look at predicates at all! :) However, it works. I think this is because the only way we can use a ${node} inside a path is as a predicate. So checking for square brackets may not be necessary?

If so, it might be good to change the variable to `is_secondary_instance` or something like that.

2021-03-05 07:52 UTC, gushil commented
> I added some tests to the issue, that may be helpful if this code ever gets refactored.

Thanks. I will add those tests.

2021-03-05 08:04 UTC, gushil commented on pyxform/survey.py
> +        is_predicate = matchobj.string.startswith("instance(")
> This `is_predicate` doesn't look at predicates at all! :) However, it works. I think this is because the only way we can use a ${node} inside a path is as a predicate. So checking for square brackets may not be necessary (?).
> 

Ok. I will add the check for square brackets.

> It might be good to change the variable to `is_secondary_instance` or something like that.

Ok. Will change the variable name in the next commit.

Thanks for the review.

2021-03-05 11:07 UTC, gushil commented
@MartijnR 

Addressed your feedbacks in recently pushed commits.

Thanks.

2021-03-05 17:26 UTC, MartijnR commented on pyxform/survey.py
> +            and re.search(r"\[(.+)\]", matchobj.string) is not None
Sorry for my confusing comment. I think the square bracket (i.e. predicate) check may not be necessary (like you had initiallly), since the use of ${node} syntax implies this. But would be good to hear what @lognaturel thinks.

2021-03-26 18:36 UTC, lognaturel requested changes
Apologies for the delay on this!

I agree with @MartijnR that looking ONLY for `instance(` as you had before is a clever way to identify expressions that will need `current`. As far as I can tell, the only place there could be a `${}` reference in such an expression is in a predicate.

The issue with this is that it will only work if a complete expression starts with `instance(`. Consider for example changing `test_repeat_using_select_with_reference_path_in_predicate_uses_current` to have `${item-counter} + instance('item')/root/item[itemindex=${item-counter}]/label` (it's nonsense but illustrates the point). Now `current()` isn't used anywhere.

2021-03-26 20:46 UTC, lognaturel commented on pyxform/tests_v1/test_repeat.py
> +    def test_repeat_with_reference_path_not_in_predicate_uses_xpath(self,):
`rep2` and `item2` don't exist so it's hard to tell what this should do. I assume you're illustrating the case where one repeat indexes into another parallel repeat? That seems like a good test to have but `rep2` should exist. I think it's also more likely that a form designer would write `${rep2}[number(${pos4})]/item2`

The test name and comment should be updated to reflect what this tests. The reference path IS inside a predicate. The key is that the node with the calculation and referenced node have the same parent.

2021-03-29 07:31 UTC, gushil commented on pyxform/tests_v1/test_repeat.py
> +    def test_repeat_with_reference_path_not_in_predicate_uses_xpath(self,):
I think this test is just for testing reference path that is not part of primary instance. Fixed.

2021-03-29 07:32 UTC, gushil commented
> Apologies for the delay on this!
> 
> I agree with @MartijnR that looking ONLY for `instance(` as you had before is a clever way to identify expressions that will need `current`. As far as I can tell, the only place there could be a `${}` reference in such an expression is in a predicate.
> 
> The issue with this is that it will only work if a complete expression starts with `instance(`. Consider for example changing `test_repeat_using_select_with_reference_path_in_predicate_uses_current` to have `${item-counter} + instance('item')/root/item[itemindex=${item-counter}]/label` (it's nonsense but illustrates the point). Now `current()` isn't used anywhere.

Thanks for the review @lognaturel 

Subsequent commit includes fixes for this as well.

2021-04-07 19:35 UTC, pbowen-oc commented
@lognaturel - Is there anything @gushil or I can do to help with this issue?

2021-04-08 22:25 UTC, lognaturel commented
> Is there anything @gushil or I can do to help with this issue?

@pbowen-oc Y'all have cycles for some of my other work? ;) Taking a look...

2021-04-08 23:12 UTC, lognaturel requested changes
Thank you, this approach makes sense to me semantically -- check to see if a ${} expression is in a predicate for a path expression that starts with `instance(`. This will slow form conversion down since every single `${}` expression will go through an extra check but I can't think of a great alternative.

I can't think of additional test cases. I would like the naming in the code changes to be a little more precise.

2021-04-08 23:12 UTC, lognaturel commented on pyxform/survey.py
> +            """check if current matchobj is a predicate and part of primary instance"""
I think we're really going to tie ourselves up in knots if this code needs to be revisited so making sure the naming is  precise is important.

Name: _in_secondary_instance_predicate
Comment: check if ${} expression represented by matchobj is in a predicate for a path expression for a secondary instance

@MartijnR any other ideas for tightening the wording?

2021-04-09 05:50 UTC, gushil commented on pyxform/survey.py
> +            """check if current matchobj is a predicate and part of primary instance"""
Thanks for the suggestion @lognaturel 
Fixed in the next commit.

2021-04-09 16:39 UTC, lognaturel approved these changes
Thanks, @gushil!

2021-04-13 19:09 UTC, merged