Node-set arguments are returned as absolute path.
XLSForm/pyxform pull request #528
Opened 2021-04-05 14:06 UTC by gushil

Closes #525

#### Why is this the best possible solution? Were any other approaches considered?
The expansion of previous working solution.

#### What are the regression risks?
None.

#### Does this change require updates to documentation? If so, please file an issue [here](https://github.com/XLSForm/xlsform.github.io) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] included test cases for core behavior and edge cases in `tests_v1`
- [x] run `nosetests` and verified all tests pass
- [x] run `black pyxform` to format code
- [x] verified that any code or assets from external sources are properly credited in comments

2021-04-06 16:55 UTC, MartijnR requested changes
Thanks! 

Apart from by using space(s) before parens, I wasn't able to break this.

2021-04-06 16:55 UTC, MartijnR commented on pyxform/survey.py
> +                    is_xpath_function = matchobj.string.find(xpath_function + "(") > -1
This fails when there are spaces before the first bracket as in `concat   (${item1}, "b")`.

2021-04-06 16:55 UTC, MartijnR commented on pyxform/tests_v1/test_repeat.py
> +                """<bind calculate="concat( /data/family/person/name , indexed-repeat( /data/family/person/age ,  /data/family , 1,  /data/family/person , 2),  ../age )" nodeset="/data/family/person/
This change in output in the first argument may sometimes be undesirable. Both relative and absolute path outputs have valid use cases. Not sure how we could please everybody. Just wanted to flag this for @lognaturel.

2021-04-07 19:33 UTC, MartijnR commented on pyxform/tests_v1/test_repeat.py
> +                """<bind calculate="concat( /data/family/person/name , indexed-repeat( /data/family/person/age ,  /data/family , 1,  /data/family/person , 2),  ../age )" nodeset="/data/family/person/
After discussing with @pbowen-oc, it may best to take concat() out of this feature and leave its behavior as is.

@lognaturel, I would have appetite in removing our concat() customization from the spec... https://getodk.github.io/xforms-spec/#fn:concat

2021-04-08 02:54 UTC, gushil commented on pyxform/tests_v1/test_repeat.py
> +                """<bind calculate="concat( /data/family/person/name , indexed-repeat( /data/family/person/age ,  /data/family , 1,  /data/family/person , 2),  ../age )" nodeset="/data/family/person/
> After discussing with @pbowen-oc, it may best to take concat() out of this feature and leave its behavior as is.
> 
> @lognaturel, I would have appetite for removing our concat() customization from our spec actually... https://getodk.github.io/xforms-spec/#fn:concat

Ok. I will remove `concat` handling in the next commit.

2021-04-08 02:55 UTC, gushil commented on pyxform/survey.py
> +                    is_xpath_function = matchobj.string.find(xpath_function + "(") > -1
You are right. Will try to fix this issue in the next commit(s).

2021-04-16 16:49 UTC, lognaturel commented
After conversation in #525, we've decided not to do this for now because it changes long-standing behavior. The effect is mostly on folks who use nested repeats but it may also result in performance issues in other contexts.

2021-04-16 16:49 UTC, closed without merging