Fixed ${} references in predicates not being expanded using current()…
XLSForm/pyxform pull request #536
Opened 2021-04-26 13:33 UTC by gushil

… if the expression contains whitespace before the reference

Closes #531 

#### Why is this the best possible solution? Were any other approaches considered?
Fixing previous working solution.

#### What are the regression risks?
None.

#### Does this change require updates to documentation? If so, please file an issue [here](https://github.com/XLSForm/xlsform.github.io) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x ] included test cases for core behavior and edge cases in `tests_v1`
- [x] run `nosetests` and verified all tests pass
- [x] run `black pyxform` to format code
- [x] verified that any code or assets from external sources are properly credited in comments

2021-05-03 20:31 UTC, MartijnR reviewed
I could not break it, though I tried quite hard. :)

2021-05-03 20:31 UTC, MartijnR commented on pyxform/tests_v1/test_repeat.py
> +        |        | calculate    | item5 |       | join(' ', instance('item')/root/item)[index = ${pos5} and ${pos1} = 1]/label)           |
Not related to this PR, but just FYI, this test shows how hard it would be (have been) to implement https://github.com/XLSForm/pyxform/issues/525. Since `join()` expects a node-set attribute but ${pos5} in this case has to be relative nonetheless since it used as a position/index....

2021-05-04 13:57 UTC, gushil commented
> I could not break it, though I tried quite hard. :)

Thanks!

2021-05-10 10:30 UTC, gushil commented
Hi @MartijnR should I make changes or we just wait for @lognaturel to chime in here?

Thanks

2021-05-11 21:23 UTC, pbowen-oc commented
@lognaturel - Will you be able to review this in the next couple days? We are working on a release to fix this and other issues and looking to get a tagged version that we can deploy for testing as soon as possible.

2021-05-12 05:07 UTC, lognaturel commented
Will try to review and release by Fri. 

@gushil please review #535. Could you also please look into why there’s a CI failure here? Have some versions changed? We want to make sure it’s green before merge.

2021-05-13 09:19 UTC, gushil commented
@lognaturel 

It looks like the failure is caused by pip version 21.1 (used by the build)

Based on https://github.com/pypa/pip/issues/9954 , by using pip version 21.1.1 (released on May 1st, a couple of days after the build happened) the warnings will be silenced.

Should we try to trigger new build? (I don't know how to do that yet)

2021-05-14 01:01 UTC, lognaturel commented
As far as I know, only @ukanga has access to the Appveyor account. When I need to re-run, I force push a change to the latest commit message. I did this here and did not change the contents of the commit.

What I'm understanding here is that #524 introduced the regular expression `instance\([^)]+\S+` to identify `instance` path expressions. This explicitly used whitespace to attempt to identify the end of a path expression starting with `instance` but I didn't really notice that or consider implications in review. All tests introduced made sure there was always a space after the `instance` path expression and not within it. This is the kind of assumption that's really valuable to describe in a PR description to make sure it's explicitly considered.

@pbowen-oc's example from the issue is particular because it has multiple predicates. I think that's important to introduce some testing around. I would have been tempted to identify the end of an expression we care about by starting with `instance(` and ending with the first `]` but the possibility of multiple predicates mean we can't do that. There should be a test that keeps us from trying that in the future.

What this PR does is remove any attempt to identify the end of an `instance` path expression. This kind of thing would be valuable to highlight in the "why is this the best solution" part of the PR template. This change means that any `${}` expression that occurs after `instance()` will get a `current()` prefix whether or not it's in a predicate. See for example `instance('item')/root/item[itemindex = ${item-counter}]/label + ${item-counter}`. The first `${item-counter}` gets a `current()` prefix which is good and expected. The second `${item-counter}` does too. This is not desirable and I don't love it but it happens that the `current()` has no effect in that case so it 's not the worst thing in the world.  I can't think of a case where the superfluous `current()` would cause problems. @MartijnR, what do you think? I don't believe we can accurately identify XPath path expressions without a parser that has knowledge of operators, function structure, opening closing brackets/braces, etc. This may be the best we can do. If we go with it, I think this case should be documented with a comment that says something like "The second reference to `item-count` should not get a `current()` prefix but we currently have no way of reliably detecting the end of an XPath path expression so any reference after `instance()` gets a `current()` prefix whether or not it's in the path expression."

We don't have to do anything about this now, but I wanted to come back to something from the initial issue that I think we didn't get quite right. At https://github.com/XLSForm/pyxform/issues/490#issuecomment-785459282, @MartijnR, you said we should only be using `current()` for XPath path expressions that start with `instance(`. I'm not really sure that's the ideal. A common thing to do is to have two parallel repeats. For example, one that builds a roster and another that asks questions about each roster member. You might want to do something like `/data/roster[position() = ${pos}]/name` in the second repeat. In that case you do need the `current()` prefix. In fact, I can't currently think of a case where it would be undesirable. You mentioned populating choices from a repeat but that's not done manually so the path expression for that would not go through this code.

2021-05-14 01:03 UTC, lognaturel requested changes
- [x] Get @MartijnR's evaluation of the extra `current()` prefixes now generated
- [x] Add tests for XPath path expressions with multiple predicates
- [x] Add test for other `${}` expressions after `instance()` that get a `current()` prefix with an explanation for why that's happening.

2021-05-14 16:39 UTC, lognaturel commented
Hmm. Now that I think about it with a clear head, wouldn't a regex that captures all strings in between `[` and `]` and uses the `current()` prefix for those have the outcome that we want? This depends on whether or not I missed something regarding predicates on nodesets in the forms.

@pbowen-oc @gushil I think this PR certainly makes a valuable improvement. If you can do the two second bullets I mentioned, I could merge and do a release. Then once we get an opportunity to hear from @MartijnR we can evaluate whether the concept I mentioned above might be promising and help capture more useful cases.

2021-05-17 04:57 UTC, pbowen-oc commented
Thanks, @lognaturel.

@gushil is working on adding tests for the cases you referenced

2021-05-17 20:49 UTC, MartijnR commented
>wouldn't a regex that captures all strings in between [ and ] and uses the current() prefix for those have the outcome that we want?

That sounds great. I agree it's better not to create unnecessary `current()` prefixes, and I'm embarrassed I didn't find `instance('item')/root/item[itemindex = ${item-counter}]/label + ${item-counter}`, because that's exactly the thing I was trying to find..... 👍 

> You might want to do something like /data/roster[position() = ${pos}]/name in the second repeat. In that case you do need the current() prefix. In fact, I can't currently think of a case where it would be undesirable. You mentioned populating choices from a repeat but that's not done manually so the path expression for that would not go through this code.

Hmmm, yes, I have a vague recollection that you mentioned this about my misunderstanding of `current()` before... I think I may have regressed and that you're right about `current()` being appropriate for all cases where a `${ref}` results in a relative path inside a predicate (so in pyxform world).

2021-05-18 04:07 UTC, lognaturel reviewed
Thanks, the new tests really help add confidence!

Am I understanding correctly that this new approach keeps the `instance()` check and then adds code to only do the current replacement inside a pair of `[]` after `instance()`? So it doesn't address my parallel repeat case (that's ok) but it does avoid putting too many `current()`s. If I understood that correctly, I'm comfortable going with this for now.

I can come up with some twisted cases with nested predicate expressions that might break but I don't think these need to be accounted for.

I believe there's now one extra loop that doesn't ever iterate more than once and I've flagged that below.

2021-05-18 04:07 UTC, lognaturel commented on pyxform/survey.py
>              for instance_match in instance_match_iter:
This no longer makes any difference since the first match will greedily capture the whole rest of the string, right?

2021-05-18 04:19 UTC, gushil commented on pyxform/survey.py
>              for instance_match in instance_match_iter:
You are right. Will be fixed in the next commit.

2021-05-18 04:21 UTC, gushil commented on pyxform/tests_v1/test_repeat.py
> +        |        | calculate    | item5 |       | (instance('item')/root/item)[index = ${pos5} and ${pos1} = 1]/label |
Ah, my bad. That comes from previous (non committed locally created) test. Will be fixed in the next commit.

2021-05-18 04:22 UTC, gushil commented on pyxform/tests_v1/test_repeat.py
> +        |        | calculate    | item5 |       | (instance('item')/root/item)[index = ${pos5} and ${pos1} = 1]/label |
I want to test reference path inside a predicate (bracketed) that includes reference in a repeat and reference outside a repeat. Is it acceptable test? Do you have any other test suggestion to achieve that?

Thanks.

2021-05-18 04:25 UTC, lognaturel commented on pyxform/tests_v1/test_repeat.py
> +        |        | calculate    | item5 |       | (instance('item')/root/item)[index = ${pos5} and ${pos1} = 1]/label |
The rest of the expression looks fine to me, I was just unclear on the significance of the parens! Agreed having a ref in the repeat and one outside is a good idea. 👍

2021-05-18 04:36 UTC, pbowen-oc commented on pyxform/tests_v1/test_repeat.py
> +        |        | calculate    | item5 |       | (instance('item')/root/item)[index = ${pos5} and ${pos1} = 1]/label |
@lognaturel - I use patterns like this when counting nodes and then iterating over them in a repeating group.

So starting with something like:
`count(instance('item')/root/group/item[name = 'test'])`

I'd keep the parentheses the same and add an ordinal predicate for my repeating group position counter:
`(instance('item')/root/group/item[name = 'test'])[position() = ${pos}]/value`

My best recollection is that this was only needed when the data didn't repeat solely at the `item` node itself but rather at nodes further up the hierarchy (like `group` in this example).

2021-05-18 05:06 UTC, lognaturel commented on pyxform/tests_v1/test_repeat.py
> +        |        | calculate    | item5 |       | (instance('item')/root/item)[index = ${pos5} and ${pos1} = 1]/label |
Yes, the parens do make sense in that case. There's no need for them in `(instance('item')/root/item)[index = ${pos5} and ${pos1} = 1]/label` but I guess they're ok around any nodeset expression.

2021-05-18 05:06 UTC, lognaturel approved these changes

2021-05-18 05:08 UTC, merged

2021-05-18 05:19 UTC, lognaturel commented
Will aim to release mid-morning tomorrow (Pacific).