Add allow-mock-accuracy parameter
XLSForm/pyxform pull request #560
Opened 2021-09-23 14:52 UTC by seadowg

Needed for getodk/collect#4768

#### Why is this the best possible solution? Were any other approaches considered?

#### What are the regression risks?

#### Does this change require updates to documentation? If so, please file an issue [here](https://github.com/XLSForm/xlsform.github.io) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] included test cases for core behavior and edge cases in `tests_v1`
- [ ] run `nosetests` and verified all tests pass
- [ ] run `black pyxform` to format code
- [ ] verified that any code or assets from external sources are properly credited in comments

2021-09-28 21:45 UTC, lognaturel commented
The required dependency update has been merged.

2021-10-04 16:28 UTC, lognaturel requested changes

2021-10-04 16:28 UTC, lognaturel commented on pyxform/tests_v1/test_allow_mock_accuracy.py
> +                'xmlns:orx="http://openrosa.org/xforms"',
This should be testing for the `http://www.opendatakit.org/xforms` namespace with `odk` prefix.

2021-10-04 16:45 UTC, seadowg commented on pyxform/tests_v1/test_allow_mock_accuracy.py
> +                'xmlns:orx="http://openrosa.org/xforms"',
Oh I think this is a mistake in `test_audio_quality` as well right (which I'm pretty sure is where I was copying from). That's probably come from somewhere else then got missed. So these tests should be matching on `'xmlns:odk="http://www.opendatakit.org/xforms"'` instead right?

2021-10-04 17:10 UTC, lognaturel approved these changes

2021-10-04 17:11 UTC, lognaturel commented on pyxform/tests_v1/test_allow_mock_accuracy.py
> +                'xmlns:orx="http://openrosa.org/xforms"',
Whoops, good call fixing those.

2021-10-04 17:11 UTC, merged