555: Add support for Python 3.9
XLSForm/pyxform pull request #580
Opened 2022-01-20 16:49 UTC by lindsay-stevens

Closes #555

#### Why is this the best possible solution? Were any other approaches considered?

A GitHub Actions yaml file was in place already with a `release` job for creating a build with Py3.8 and linux (ubuntu) and uploading it to PyPI. This PR updates the yaml to add jobs for:

- `lint`, with Py3.8 on linux, by running `black`, `isort`, `flake8`, and `pycodestyle`
- `test`, with Py3.7, 3.8, and 3.9 on linux, macos, and windows, by running `nosetests`
  - At the end of the `test` job the sdist and wheel are uploaded as Artifacts ([example here](https://github.com/lindsay-stevens/pyxform/actions/runs/1724468708)).

The above more or less covers what the AppVeyor and CircleCI configurations are doing. So if this all looks good I could add removal of those CI dotfiles to this PR to close out #568 as well.

Some minor changes were required for Py3.9 compatibility. These are noted in e9c77ab and 3b21ce9, and involved removing a method call and a kwarg which were deprecated since Py3.2 and Py3.1 respectively.

#### What are the regression risks?

Unlikely, but maybe the test CI environments are slightly different. But the tests pass all the same.

#### Does this change require updates to documentation? If so, please file an issue [here](https://github.com/XLSForm/xlsform.github.io) and include the link below.

No, it would only affect developers.

#### Before submitting this PR, please make sure you have:
- [x] included test cases for core behavior and edge cases in `tests`
- [x] run `nosetests` and verified all tests pass
- [x] run `black pyxform tests` to format code
- [x] verified that any code or assets from external sources are properly credited in comments

2022-01-20 22:32 UTC, lognaturel reviewed
Looks great to me and I'm in favor of removing reliance on codecov, circleci and appveyor. Doing that in this PR seems fine.

Let's give @yanokwa a few days to review before merging.

2022-01-20 22:34 UTC, lognaturel requested changes
Realized the workflow should probably be renamed since PyPI is only involved for releases. Maybe just `pyxform`?

2022-01-20 22:37 UTC, lognaturel commented on .github/workflows/pypi.yml
>  on: [push, pull_request, release]
I suggested renaming the workflow but maybe it makes more sense to have a "verify" workflow that is run on all these actions with jobs `lint` and `test`. And then a separate "release" workflow that runs only on release. That way you don't need the conditional in the `release` job and overall it would feel more event-based.

2022-01-24 15:43 UTC, lindsay-stevens commented on .github/workflows/pypi.yml
>  on: [push, pull_request, release]
Thanks, renamed existing workflow PyPI -> `release`, and moved test/lint jobs into new `verify` workflow.

2022-01-24 15:45 UTC, lindsay-stevens commented
`./.circleci/config.yml` and `./appveyor.yml` have been deleted so these checks failed. `./.coveragerc` also deleted.

2022-01-27 05:13 UTC, lognaturel approved these changes

2022-01-27 05:14 UTC, merged