Add rows to parameters column for text type
XLSForm/pyxform pull request #667
Opened 2023-11-21 02:02 UTC by grzesiek2010

Closes #616 

#### Why is this the best possible solution? Were any other approaches considered?

#### What are the regression risks?

#### Does this change require updates to documentation? If so, please file an issue [here](https://github.com/XLSForm/xlsform.github.io) and include the link below.

#### Before submitting this PR, please make sure you have:
- [ ] included test cases for core behavior and edge cases in `tests`
- [ ] run `nosetests` and verified all tests pass
- [ ] run `black pyxform tests` to format code
- [ ] verified that any code or assets from external sources are properly credited in comments

2023-11-22 15:08 UTC, lindsay-stevens requested changes

2023-11-22 15:08 UTC, lindsay-stevens commented on pyxform/xls2json.py
> +            if "rows" in parameters.keys():
Please validate the allowed parameters - see usage of `parameters_generic.validate(` for geopoint for example.

2023-11-22 15:08 UTC, lindsay-stevens commented on pyxform/xls2json.py
> +                    raise PyXFormError("Parameter rows must have an integer value.")
Please include the row number in the error message.

2023-11-22 15:08 UTC, lindsay-stevens commented on tests/test_rows.py
> +# -*- coding: utf-8 -*-
Please prefix the file name e.g. `test_parameters_rows.py` so it's clearer that this is about a parameter called 'rows' and easier to find.

2023-11-22 15:08 UTC, lindsay-stevens commented on tests/test_rows.py
> +class TestRows(PyxformTestCase):
What happens if you provide both `body::rows` and the rows parameter - either with the same value or different values? Does one of them "win" (if so, which)? Should an error be raised if both are present?

2023-11-22 15:15 UTC, lindsay-stevens commented
> Nothing to discuss here.

I mean, OK, but that's a bit flippant. You could say whether or not you followed the existing patterns for parameters (and why), whether or not you searched for other issues that might overlap with the linked issue, whether or not you tested the XForm output with Collect and/or Enketo, etc.

I often use PR descriptions, issues, and commit messages to do code archaeology to understand why things are a certain way, so adding some detail is worth the effort even if it seems obvious now.

2023-11-23 20:35 UTC, grzesiek2010 commented on pyxform/xls2json.py
> +            if "rows" in parameters.keys():
Done.

2023-11-23 20:35 UTC, grzesiek2010 commented on pyxform/xls2json.py
> +                    raise PyXFormError("Parameter rows must have an integer value.")
Done.

2023-11-23 20:36 UTC, grzesiek2010 commented on tests/test_rows.py
> +# -*- coding: utf-8 -*-
Done.

2023-11-23 20:44 UTC, grzesiek2010 commented
> I mean, OK, but that's a bit flippant. You could say whether or not you followed the existing patterns for parameters (and why), whether or not you searched for other issues that might overlap with the linked issue, whether or not you tested the XForm output with Collect and/or Enketo, etc.

> I often use PR descriptions, issues, and commit messages to do code archaeology to understand why things are a certain way, so adding some detail is worth the effort even if it seems obvious now.

Yeah, that makes sense. Even if something is obvious adding a short description might be valuable for other devs.

2023-11-23 20:49 UTC, grzesiek2010 commented on tests/test_rows.py
> +class TestRows(PyxformTestCase):
The value specified in the parameters wins. I've added a test to check it https://github.com/XLSForm/pyxform/pull/667/files#diff-abdea13ad59db09df2c93db5a3d79d441fa45fbc8615a597ccf7d970cb253c32R22
I think that's ok since it's the new and recommended way of setting rows and body::rows should be deprecated and maybe even removed at some point.

2023-11-24 07:12 UTC, lindsay-stevens approved these changes

2023-11-24 07:12 UTC, merged

2023-11-24 07:13 UTC, lindsay-stevens commented
@grzesiek2010 thanks!